# name: SonarQube
# on:
#   pull_request:
#     branches:
#       - master
#       - develop
#       - staging
# jobs:
#   build:
#     name: Scaning with SonarQube
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ./backend
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           fetch-depth: 0
#       - name: Install dependencies
#         run: npm install
#       - name: Test and coverage
#         run: npm run test --coverage
#       - uses: sonarsource/sonarqube-scan-action@master
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
#       # If you wish to fail your job when the Quality Gate is red, uncomment the
#       # following lines. This would typically be used to fail a deployment.
#       - uses: sonarsource/sonarqube-quality-gate-action@master
#         timeout-minutes: 5
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
